import { Canvas } from '@react-three/fiber'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { createRef, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import BlackSheet from '../components/BlackSheet'
import Chapter from '../components/Chapter'
import IndexHolder from '../components/IndexHolder'
import BioPage from '../components/Pages/Bio'
import IntroPage from '../components/Pages/Intro'
import PageWrapper from '../components/Pages/PageWrapper'
import ScrollBar from '../components/ScrollBar'
import { getScrollPosition, scrollCalculator } from '../components/utils/scroll-helpers'

const Home: NextPage = () => {
  const [scroll, setScroll] = useState<number>(0);
  const divRef: React.LegacyRef<HTMLDivElement> | undefined = createRef();
  let timer: number;

  const Scroller: (this: HTMLDivElement, ev: WheelEvent) => any = (e: any) => {
    e.preventDefault();
    const newValue = scrollCalculator(e.wheelDeltaY, e.wheelDeltaX);

    if (newValue != null) {
      setScroll(prev => (prev - newValue));
    }
  }

  const onChapterClickEventHandler = (position: number) => {
    setScroll(getScrollPosition(position));
  }


  useEffect(() => {
    divRef.current?.addEventListener("wheel", Scroller);
  }, [])

  return (
    <div ref={divRef != null ? divRef : null} style={{ width: "100%", display: "flex", justifyContent: "center" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "90%", maxWidth: "1000px", minWidth: "300px", backgroundColor: "red", height: "100vh" }}>
        <Canvas style={{ width: "100%", backgroundColor: "white" }}>
          <ambientLight />
          <spotLight castShadow={true} position={[100, 100, 100]} />
          <pointLight position={[100, 100, 100]} />
          <pointLight position={[100, 100, 100]} />
          <BlackSheet scroll={scroll} position={[0, 0, 0]} />
        </Canvas>
      </div>
      <PageWrapper scroll={scroll} zone={[1.4, 2.24]}>
        <BioPage />
      </PageWrapper>
      <PageWrapper scroll={scroll} zone={[0, 1.39]}>
        <IntroPage />
      </PageWrapper>
      <IndexHolder>
        <ScrollBar {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} position={5} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"bio"} position={20} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"skills"} position={40} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"curriculum"} position={60} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"monkey"} position={80} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} position={95} {...{ scroll }} />
      </IndexHolder>
    </div>)
}

export default Home
