import { Canvas } from '@react-three/fiber'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { createRef, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import BlackSheet from '../components/BlackSheet'
import Chapter from '../components/Chapter'
import IndexHolder from '../components/IndexHolder'
import BioPage from '../components/Pages/Bio'
import IntroPage from '../components/Pages/Intro'
import PageWrapper from '../components/Pages/PageWrapper'
import ScrollBar from '../components/ScrollBar'
import { getClosestThreshold, getNewTouchScroll, getScrollPosition, scrollCalculator } from '../components/utils/scroll-helpers'
import { thresHolds } from '../components/utils/app-config'

const Home: NextPage = () => {
  const [scroll, setScroll] = useState(0);
  const [currentTouch, setCurrentTouch] = useState<{ Y?: number, X?: number }>({});
  let timer: NodeJS.Timeout;

  const divRef: React.LegacyRef<HTMLDivElement> | undefined = createRef();

  const Scroller: (e: any) => any = (e: any) => {
    e.preventDefault();
    clearTimeout(timer);

    const Y = e.wheelDeltaY;
    const X = e.wheelDeltaX;
    const newValue = scrollCalculator(Y, X);
    console.log(newValue);

    setScroll(prev => (prev - newValue));
    timer = setTimeout(() => {
      console.log("scroll finished");
      // const newScroll = scroll;
      // const threshold = getClosestThreshold(newScroll);
      // if (threshold) setScroll(threshold+2.5);
    }, 300)

  }

  function MobileScroller(this: HTMLDivElement, e: TouchEvent) {
    e.preventDefault();
    const Y = e.changedTouches[0].clientY;
    const X = e.changedTouches[0].clientX;
    console.log("scrolling!!!", Y, X);
    clearTimeout(timer);
    setCurrentTouch({ Y: Y, X: X })
    if (currentTouch.Y && currentTouch.X) {
      const newScroll = getNewTouchScroll({ X: currentTouch.X, Y: currentTouch.Y }, { X: X, Y: Y })
    }
    // setScroll(prev => (getNewScroll))



    timer = setTimeout(() => {
      console.log("scroll finished");
      // const threshold = getClosestThreshold(scroll);
      // if (threshold) setScroll(threshold);
    }, 300)

  }


  const onChapterClickEventHandler = (position: number) => {
    setScroll(getScrollPosition(position));
  }


  useEffect(() => {
    divRef.current?.addEventListener("wheel", Scroller);
    divRef.current?.addEventListener("touchmove", MobileScroller);
  }, [])

  return (
    <div ref={divRef != null ? divRef : null} style={{ width: "100%", height: "100%", display: "flex", justifyContent: "center", position: "absolute" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/ReenieBeanie/ReenieBeanie.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <div style={{ width: "90%", maxWidth: "1000px", minWidth: "300px", backgroundColor: "red", height: "100vh", }}>
        <Canvas style={{ width: "100%", backgroundColor: "white" }}>
          <ambientLight />
          <spotLight castShadow={true} position={[100, 100, 100]} />
          <pointLight position={[100, 100, 100]} />
          <pointLight position={[100, 100, 100]} />
          <BlackSheet scroll={scroll} position={[0, 0, 0]} />
        </Canvas>
      </div>
      <PageWrapper scroll={scroll} zone={[0, thresHolds[0]]}>
        <IntroPage />
      </PageWrapper>
      <PageWrapper scroll={scroll} zone={[thresHolds[0] + 0.01, thresHolds[1]]}>
        <BioPage />
      </PageWrapper>
      <IndexHolder>
        <ScrollBar {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} position={5} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"bio"} position={20} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"skills"} position={40} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"curriculum"} position={60} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} title={"social"} position={80} {...{ scroll }} />
        <Chapter onClickEvent={onChapterClickEventHandler} position={95} {...{ scroll }} />
      </IndexHolder>
    </div>
  )
}

export default Home



